project:
  type: website
  output-dir: docs

website:
  title: "Amanda Overbye"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resources.qmd
        text: Resources
      - blog_posts.qmd

format:
  html:
    theme: 
      light: united
      dark: superhero
    css: styles.css
    toc: false
    page-layout: full

editor: visual

