project:
  type: website
  output-dir: docs

website:
  title: "Amanda Overbye"
  favicon: logo_white_clean.png
  navbar:
    logo: logo_white_clean.png
    title: False
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resources.qmd
        text: Resources
      - blog_posts.qmd

format:
  html:
    theme: styles.scss
    css: styles.css
    toc: false
    page-layout: full

editor: visual

